// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-profile.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var profile = {
  name: "Kanhaiya Kumar",
  title: "Backend Developer",
  location: "Bengaluru, India",
  summary: "Backend Developer building AI-powered, production-grade systems with Java 21, Spring Boot and Hexagonal Architecture. Integrates Google Gemini LLMs, 768-d embeddings and PostgreSQL pgvector to ship intelligent recruitment workflows.",
  highlights: [
    "AI-Powered Backend \u2014 Gemini 2.0 Flash LLM integration, ~90% CV parsing accuracy & AI fitness scoring",
    "Semantic Search \u2014 pgvector + 768-d embeddings for real-time auto-suggestion at scale",
    "Hexagonal Architecture \u2014 Java 21 & Spring Boot with cleanly separated adapters",
    "Test-Driven Delivery \u2014 JUnit & Mockito with 85\u201390%+ coverage and 40% faster CI/CD"
  ],
  resumeUrl: "/Kanhaiya_Kumar_Resume.pdf"
};
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Get profile",
  description: "Get Kanhaiya Kumar's professional profile summary, title, location and highlights.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
    structuredContent: profile
  })
});

// src/lib/mcp/tools/get-skills.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var skills = [
  { category: "Languages", skills: ["Java 21"] },
  { category: "Frameworks", skills: ["Spring Boot", "Spring MVC", "Spring Data JPA", "Spring Security", "Hibernate"] },
  { category: "Backend & Architecture", skills: ["REST APIs", "Microservices", "Hexagonal Architecture", "Rate Limiting"] },
  { category: "AI / Intelligent Systems", skills: ["LLM Integration", "Google Gemini API", "AI-powered CV Parsing", "Semantic Search", "Embeddings", "Document Processing", "pgvector"] },
  { category: "Databases", skills: ["MySQL", "PostgreSQL", "pgvector"] },
  { category: "Tools", skills: ["Gradle", "Git", "GitHub", "Docker", "Postman", "Swagger", "Sentry", "Jira"] },
  { category: "Integrations", skills: ["Meta WhatsApp Cloud API", "Razorpay Payment Integration", "MSG91 / Twilio SMS"] },
  { category: "Testing", skills: ["JUnit", "Mockito"] },
  { category: "Cloud", skills: ["AWS", "Azure"] },
  { category: "Core CS", skills: ["DSA", "OOPs", "Collections", "Java 8+"] },
  { category: "Methodology", skills: ["Agile", "TDD", "Code Review"] }
];
var get_skills_default = defineTool2({
  name: "get_skills",
  title: "Get skills",
  description: "Get Kanhaiya Kumar's technical skills grouped by category (languages, frameworks, AI, databases, etc.).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(skills, null, 2) }],
    structuredContent: { categories: skills }
  })
});

// src/lib/mcp/tools/get-experience.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var experiences = [
  {
    company: "Duru Cooperation",
    role: "Backend Developer \u2013 Product Development",
    period: "July 2025 - Present",
    location: "Bengaluru, India",
    product: "Duruper \u2013 Global Recruitment Platform",
    techStack: "Java 21 \xB7 Spring Boot \xB7 Hexagonal Architecture \xB7 Google Gemini \xB7 PostgreSQL \xB7 pgvector \xB7 REST",
    achievements: [
      "Building backend features for Duruper using Java 21 and Spring Boot with Hexagonal Architecture (Ports & Adapters).",
      "Architected an AI-powered CV Parsing system with Apache Tika and Gemini 2.5 Flash \u2014 ~80% less manual processing time, ~90% parsing accuracy.",
      "Built an AI Candidate Fitness Scoring system generating 0\u2013100 job-fit scores using Gemini LLM.",
      "Developed an AI job classification engine using Gemini embeddings (768-d) and PostgreSQL pgvector cosine similarity.",
      "Reduced CI/CD deployment time ~40% (18 \u2192 11 min) via Gradle caching in GitHub Actions."
    ]
  },
  {
    company: "Cognizant Technology Solutions",
    role: "Software Engineer",
    period: "May 2022 - Nov 2024",
    location: "Bengaluru, India",
    techStack: "Java \xB7 Spring Boot \xB7 Microservices \xB7 MySQL",
    achievements: [
      "Designed scalable RESTful APIs with Spring Boot, improving response times by 10%.",
      "Optimized database queries using JPA and MySQL, reducing retrieval times by 15%.",
      "Achieved 90%+ test coverage via comprehensive unit and integration tests.",
      "Conducted 100+ technical interviews for Java backend developer positions."
    ]
  },
  {
    company: "Agimus Technologies",
    role: "IoT Intern",
    period: "Internship",
    location: "Remote",
    techStack: "IoT \xB7 Embedded systems",
    achievements: ["Worked on IoT-based projects and gained hands-on experience with emerging technologies."]
  }
];
var get_experience_default = defineTool3({
  name: "get_experience",
  title: "Get work experience",
  description: "Get Kanhaiya Kumar's work experience history with roles, companies, tech stacks and achievements.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(experiences, null, 2) }],
    structuredContent: { experiences }
  })
});

// src/lib/mcp/tools/get-contact.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
var contact = {
  email: "kanhaiya.kk20598@gmail.com",
  phone: "+91 8804936144",
  location: "Bengaluru, India",
  linkedin: "https://www.linkedin.com/in/kanhaiya20598/",
  github: "https://github.com/kanhaiyakk",
  openTo: "Backend Development, Microservices, and System Design opportunities."
};
var get_contact_default = defineTool4({
  name: "get_contact",
  title: "Get contact info",
  description: "Get Kanhaiya Kumar's public contact details and social links (email, phone, LinkedIn, GitHub).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(contact, null, 2) }],
    structuredContent: contact
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "kanhaiya-kumar-portfolio-mcp",
  title: "Kanhaiya Kumar Portfolio MCP",
  version: "0.1.0",
  instructions: "Tools for exploring Kanhaiya Kumar's developer portfolio. Use `get_profile` for a summary, `get_skills` for the tech stack, `get_experience` for work history, and `get_contact` for public contact details.",
  tools: [get_profile_default, get_skills_default, get_experience_default, get_contact_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
